import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import type { AppConfig } from '../config/env.js';
import { sha256 } from '../utils/crypto.js';
import { apiFileUrls, extToType, isSafeKey, keyFor, type FileKind, type PutResult, type Storage } from './storage.js';

/**
 * Files on the local filesystem.
 *
 * Right for development and for the test suite, where it needs no cloud account
 * and no network. On Cloud Run it also works but the disk is EPHEMERAL — a new
 * revision or a scaled instance starts empty — so a real deployment swaps in a
 * cloud driver (`STORAGE_DRIVER=gcs`). That limit is a deploy concern,
 * documented in the deploy guide, not a code one: the interface is identical.
 *
 * The key is generated by the server (a uuid under a fixed prefix), never taken
 * from the client, and every path is resolved and checked to stay inside the
 * upload directory, so a crafted key cannot escape it.
 */
export function createDiskStorage(config: AppConfig): Storage {
  const root = resolve(process.cwd(), config.UPLOAD_DIR);

  const pathFor = (key: string): string => {
    if (!isSafeKey(key)) throw new Error('unsafe storage key');
    const full = resolve(root, key);
    if (full !== root && !full.startsWith(root + sep)) throw new Error('storage key escapes the upload directory');
    return full;
  };

  const urls = apiFileUrls(config);

  return {
    async put(input: { kind: FileKind; ext: string; body: Buffer }): Promise<PutResult> {
      const key = keyFor(input.kind, input.ext);
      const full = pathFor(key);
      await mkdir(dirname(full), { recursive: true });
      await writeFile(full, input.body);
      return { key, sha256: sha256(input.body), bytes: input.body.byteLength };
    },

    async delete(key: string): Promise<void> {
      try {
        await rm(pathFor(key));
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
      }
    },

    async read(key: string): Promise<{ body: Buffer; contentType: string } | null> {
      try {
        const body = await readFile(pathFor(key));
        return { body, contentType: extToType(key) };
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw err;
      }
    },

    signedUrl: urls.signedUrl,
    publicUrl: urls.publicUrl,
  };
}
